import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
//Redux
import {
  useAppSelector,
} from '../app/hooks';
import { selectCount } from '../store/selectors';

const Home: NextPage = () => {
  const count = useAppSelector(selectCount);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>سلام </h1>
        <Link href='/posts/first-post' >
          <a className={styles.link} >رفتن به صفحه پست </a>
        </Link>
      </main>
    </div>
  )
}

export default Home
