import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
// Material UI
import { Button } from '@mui/material'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>my first next app</h1>
        <Link href='/posts/first-post' >
          <a className={styles.link} >GO TO FIRST POST</a>
        </Link>

        <Button variant='outlined' >
          My Frist Button
        </Button>
      </main>
    </div>
  )
}

export default Home
